### PR TITLE
Do camera stuff

### PR DESCRIPTION
**Pull request by sagesmith-wf**
#### Changes
- Commented out unused dependencies
- Removed camera library dependency
- Wrote code to take pictures
- Wrote code to take pictures on interval

Please Review: @irish3725 @sdilts

### CODE REVIEW

**Comment by sdilts** [comment]
Looks good. I will modify this so that the filename gets put into a queue everytime a picture is taken. Something like https://github.com/sdilts/image_tracker/blob/camera_setup/src/main/java/csci432/CameraTimer.java, but cleaner and keeping your interface

**Comment by sdilts** [comment]
What exactly "failed" on this? @sagersmith8 It looks fine to me.

**Comment by sagersmith8** [comment]
This will have merge conflicts with Alex's so I will wait until after it is merged to fix. It wants unit tests on camera files so I will add those at the same time I fix the merge conflicts.

**Comment by sagersmith8** [comment]
It is currently failing because I didn't add unit tests for the camera stuff so I didn't hit my target of 25%

**Pull request merged**
